export const PINATA_JWT = process.env.NEXT_PUBLIC_PINATA_JWT
export const LENS_HUB_CONTRACT = process.env.NEXT_PUBLIC_LENS_HUB_CONTRACT
export const LENS_PERIPHERY_CONTRACT = process.env.NEXT_PUBLIC_LENS_PERIPHERY_CONTRACT
